### ISSUE TITLE
sobre el gpe_fft_v0.py

### ISSUE THREAD

**Issue by brunojulia** [brunojulia/ultracoldUB#1]
Antonio, que paquetes hay que tener instalados y como se compilan/corren los codigos que has subido? Seria bueno añadir esta informacion a la cabecera del programa.

De hecho si compilo con 
python gpe_fft_v0.py
me dice, 
   get_ipython().magic('matplotlib inline')
NameError: name 'get_ipython' is not defined

si comento esa linea parece que compila...

**Comment by brunojulia** [comment]
De hecho si compilo con 
python gpe_fft_v0.py
me dice, 
   get_ipython().magic('matplotlib inline')
NameError: name 'get_ipython' is not defined

**Comment by antoniommateo** [comment]
De momento, lo mejor, si puedes, es usar un notebook del python (para el .ipynb) y también puedes usar un editor de shell de python (para el .py) como el "idle". Ricardo me comenta que podíamos trabajar todos con éste, aunque yo lo he hecho con el notebook.
Respecto a comentar la línea del matplotlib no hay problema, sólo es para dibujar las gráficas en el notebook.
Más adelante modificaré todo para que sea más automático, principalmente leer datos desde fichero o de manera interactiva, cambiar la integración temporal, mejorar la estructura, etc. Por ahora es mejor recurrir al entorno gráfico del notebook.
Una última cosa que ha resultado de una conversación con Ricardo: deberíamos usar un estilo común de programación (que ya acordaremos).
