### ISSUE TITLE
new python code .py

### ISSUE THREAD

**Issue by antoniommateo** [brunojulia/ultracoldUB#2]
Hola a todos, aunque no sirve para casi nada (quiero decir que en la versión shell aún hay que modificar los datos a mano si uno quiere calcular casos nuevos), he puesto la versión nueva del fichero gpe_fft_v0.py para que deje correr desde la shell sin problemas y dibujando las gráficas en pantalla

**Comment by antoniommateo** [comment]
Un útimo comentario al respecto del gpe_fft_v0.py. 
Si alquien quiere hacer alguna prueba con el oscilador armónico, conviene que ponga la frecuencia de oscilador a 1 para que obtenga todas las energías y/o distancias en unidades del oscilador.

**Comment by ghost** [comment]
Si todo va bien de aquí a nada estara colgado un script que funciona en python 2.7 con un modelin muy tonto pero que servira para copiar la representación grafica.
Se trata de un oscilador harmónico vertical. 
AL principio del script hay explicaciones del 'state-of-the art'.
Si alguin toca algo que le ponga un numerito al nombre (por ejemplo si es spring3.py que le ponga springs3-1.py) para no machacar este que si va.
